const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349042912671";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_05_48_10_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc2LFxuICAgICAgICAyMTYsXG4gICAgICAgIDYxLFxuICAgICAgICAyMTksXG4gICAgICAgIDE5MCxcbiAgICAgICAgODYsXG4gICAgICAgIDQ5LFxuICAgICAgICAzOCxcbiAgICAgICAgMTM4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjE5LFxuICAgICAgICAxOTUsXG4gICAgICAgIDk1LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE5MSxcbiAgICAgICAgOTgsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjM4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE3MixcbiAgICAgICAgNjgsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTgzLFxuICAgICAgICA2OSxcbiAgICAgICAgODYsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTA5LFxuICAgICAgICA1MSxcbiAgICAgICAgMzIsXG4gICAgICAgIDIxMixcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjEzLFxuICAgICAgICAxNDksXG4gICAgICAgIDIxMCxcbiAgICAgICAgNSxcbiAgICAgICAgMTcsXG4gICAgICAgIDc4LFxuICAgICAgICAxNDAsXG4gICAgICAgIDg5LFxuICAgICAgICAxMyxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMzIsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMSxcbiAgICAgICAgMTM4LFxuICAgICAgICAyNDcsXG4gICAgICAgIDc1LFxuICAgICAgICA4NSxcbiAgICAgICAgMTgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjAxLFxuICAgICAgICAzOSxcbiAgICAgICAgMjA2LFxuICAgICAgICAyNDksXG4gICAgICAgIDEyMyxcbiAgICAgICAgNTZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTMzLFxuICAgICAgICAxMjksXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxODAsXG4gICAgICAgIDMyLFxuICAgICAgICAyMjksXG4gICAgICAgIDIxOCxcbiAgICAgICAgODAsXG4gICAgICAgIDg0LFxuICAgICAgICAxMCxcbiAgICAgICAgMTk3LFxuICAgICAgICAyNyxcbiAgICAgICAgMjUsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTgsXG4gICAgICAgIDkxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTYxLFxuICAgICAgICAyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMzUsXG4gICAgICAgIDk3LFxuICAgICAgICAxNjgsXG4gICAgICAgIDMwLFxuICAgICAgICA5OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDUsXG4gICAgICAgIDkzLFxuICAgICAgICAyNTUsXG4gICAgICAgIDkxLFxuICAgICAgICA5NyxcbiAgICAgICAgNTAsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTA2LFxuICAgICAgICA2OSxcbiAgICAgICAgMjI0LFxuICAgICAgICAxMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICA2NCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgNjcsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMzMsXG4gICAgICAgIDkzLFxuICAgICAgICAxMjUsXG4gICAgICAgIDMxLFxuICAgICAgICA4MyxcbiAgICAgICAgMCxcbiAgICAgICAgODQsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDg5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNzYsXG4gICAgICAgIDcyLFxuICAgICAgICAyNTEsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTY1LFxuICAgICAgICA2MixcbiAgICAgICAgMzAsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjE3LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTg3LFxuICAgICAgICA1MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxOTIsXG4gICAgICAgIDM5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE3LFxuICAgICAgICAxOSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxOTcsXG4gICAgICAgIDYyLFxuICAgICAgICAxMTIsXG4gICAgICAgIDI4LFxuICAgICAgICA4OSxcbiAgICAgICAgMjE4LFxuICAgICAgICA1MyxcbiAgICAgICAgMTQzLFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzQsXG4gICAgICAgIDEzLFxuICAgICAgICAxODIsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTY5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDgsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTUsXG4gICAgICAgIDIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjM2LFxuICAgICAgICAxMDksXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTczLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTkwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTQ3LFxuICAgICAgICA4MyxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMjgsXG4gICAgICAgIDYyLFxuICAgICAgICAzMyxcbiAgICAgICAgMTUwLFxuICAgICAgICA2MyxcbiAgICAgICAgMTE2LFxuICAgICAgICA0MyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxMDRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgODVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgNjZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDksXG4gICAgICAgIDM0LFxuICAgICAgICA2NixcbiAgICAgICAgMjM5LFxuICAgICAgICAxMjYsXG4gICAgICAgIDUsXG4gICAgICAgIDg2LFxuICAgICAgICAyMTksXG4gICAgICAgIDYzLFxuICAgICAgICA2OCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA3MSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA0LFxuICAgICAgICA4MCxcbiAgICAgICAgMTA3LFxuICAgICAgICA3NixcbiAgICAgICAgMTMwLFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTIzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjIsXG4gICAgICAgIDgxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMzIsXG4gICAgICAgIDIxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjU0LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjA3LFxuICAgICAgICAxOTksXG4gICAgICAgIDk0LFxuICAgICAgICAxNDMsXG4gICAgICAgIDg3LFxuICAgICAgICAyOCxcbiAgICAgICAgNzUsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNzgsXG4gICAgICAgIDY3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNTksXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTA1LFxuICAgICAgICA1NyxcbiAgICAgICAgMTIwLFxuICAgICAgICA2MCxcbiAgICAgICAgNTYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTU4LFxuICAgICAgICAxLFxuICAgICAgICAxMzdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEwNixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ6TCttenR2MlNtcTFhRjJSbEZCYWdvdEdWN2JZMWdzRUFUald0azFFWDR3PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkwNDI5MTI2NzFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjY5MkZGNUIwMEMxOEM4QTAzOTgzMDZBOEREODRFQkU0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzc2MTY5OVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkwNDI5MTI2NzFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkVFNTlCMThEMjZDQjc4OEVBNEMxRDVBNUFDRTg3MjY1XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzc2MTcwMFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCIxYmhQX2FJSVNKMkFWRERydjA5VmpBXCIsXG4gIFwicGhvbmVJZFwiOiBcIjgyOTExMWYxLTc1NjUtNDYyMC1iYTM2LWNlYzVjYTZmN2E1M1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4OCxcbiAgICAgIDIyMixcbiAgICAgIDIsXG4gICAgICAxMTAsXG4gICAgICA1NSxcbiAgICAgIDUzLFxuICAgICAgMTA0LFxuICAgICAgMTM2LFxuICAgICAgMzgsXG4gICAgICAxMjAsXG4gICAgICAyMTQsXG4gICAgICAxOTAsXG4gICAgICAzMyxcbiAgICAgIDExMCxcbiAgICAgIDEsXG4gICAgICAxNjEsXG4gICAgICAzMCxcbiAgICAgIDEyOSxcbiAgICAgIDkwLFxuICAgICAgMTYyXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2MCxcbiAgICAgIDksXG4gICAgICAyMzQsXG4gICAgICAxNyxcbiAgICAgIDY5LFxuICAgICAgOTksXG4gICAgICAzMixcbiAgICAgIDEyNixcbiAgICAgIDYxLFxuICAgICAgNyxcbiAgICAgIDI0LFxuICAgICAgMjQzLFxuICAgICAgMTg4LFxuICAgICAgNDYsXG4gICAgICAxMTQsXG4gICAgICAzMSxcbiAgICAgIDIwMyxcbiAgICAgIDEzLFxuICAgICAgMTY0LFxuICAgICAgNzBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUjFESFRHNTFcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkwNDI5MTI2NzE6MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjE2MTk2MzU2MDMwNDk0OjFAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiS2luZyBFXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTzYrMlZRUW5KcnV0d1lZQVNBQUtBQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJ1cVhmblo0M1FkOThIdzVTZUxPQVhXdis4aWdLeGRmN1Z0aUltLzhQOG00PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInhRVEppdzJtSXduNTJGTjZZVHFIdFltcXhkeGl0VkxQUk1KVXV0Z0tDbUZzU3ZpN1E1MnY4bXpwSjY2ZWZzbjVITXRpZTZuRWs0RSt0RWhOVkp5eEFBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlB5WGgwV3JaWllMR0JVUGxlSGhxUExwcnBidCtBTFRIeUQxMmVXd3FxT09uUEphdUNpZUt6NUo5RjhUZmxlamJaSC9VcFIwOFBLU3VrbmNyZ3F5Zmp3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwNDI5MTI2NzE6MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDExMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3NzYxNjk1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRVdHXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFFV0cuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJnVXVEaXVTVlp4emlKUDlmd28vZEZzZEY3dVBSVmRkV2t0ZE9ZYXc1M0pvPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE3NzYyNjk5MCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI3NzYxNjk3NTk1XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
